In [5]:
import sys
lst=[80, 17, 6, 86, 46, 5, 70, 32, 31, 95, 28, 45, 61, 92, 99, 24, 7, 35, 62, 29, 36, 11, 93, 76, 88, 87, 55, 71, 22, 44, 23, 94, 67, 74, 73, 89, 10, 43, 15, 37, 85, 56, 47, 60, 98, 26, 1, 8, 66, 2, 13, 77, 72, 90, 100, 58, 27, 48, 20, 33, 34, 38, 18, 4, 82, 91, 75, 42, 83, 78, 68, 21, 65, 25, 53, 50, 96, 16, 3, 79, 97, 57, 64, 40, 19, 41, 69, 14, 39, 9, 59, 63, 52, 54, 49, 81, 12, 30, 84, 51]
print(lst,type(lst))
print("Memory Space:",sys.getsizeof(lst))

[80, 17, 6, 86, 46, 5, 70, 32, 31, 95, 28, 45, 61, 92, 99, 24, 7, 35, 62, 29, 36, 11, 93, 76, 88, 87, 55, 71, 22, 44, 23, 94, 67, 74, 73, 89, 10, 43, 15, 37, 85, 56, 47, 60, 98, 26, 1, 8, 66, 2, 13, 77, 72, 90, 100, 58, 27, 48, 20, 33, 34, 38, 18, 4, 82, 91, 75, 42, 83, 78, 68, 21, 65, 25, 53, 50, 96, 16, 3, 79, 97, 57, 64, 40, 19, 41, 69, 14, 39, 9, 59, 63, 52, 54, 49, 81, 12, 30, 84, 51] <class 'list'>
Memory Space: 920


In [6]:
import numpy as an
import sys
lst=[80, 17, 6, 86, 46, 5, 70, 32, 31, 95, 28, 45, 61, 92, 99, 24, 7, 35, 62, 29, 36, 11, 93, 76, 88, 87, 55, 71, 22, 44, 23, 94, 67, 74, 73, 89, 10, 43, 15, 37, 85, 56, 47, 60, 98, 26, 1, 8, 66, 2, 13, 77, 72, 90, 100, 58, 27, 48, 20, 33, 34, 38, 18, 4, 82, 91, 75, 42, 83, 78, 68, 21, 65, 25, 53, 50, 96, 16, 3, 79, 97, 57, 64, 40, 19, 41, 69, 14, 39, 9, 59, 63, 52, 54, 49, 81, 12, 30, 84, 51]
b=an.array(lst)
print(b,type(b))
print("Memory Space:",sys.getsizeof(b))

[ 80  17   6  86  46   5  70  32  31  95  28  45  61  92  99  24   7  35
  62  29  36  11  93  76  88  87  55  71  22  44  23  94  67  74  73  89
  10  43  15  37  85  56  47  60  98  26   1   8  66   2  13  77  72  90
 100  58  27  48  20  33  34  38  18   4  82  91  75  42  83  78  68  21
  65  25  53  50  96  16   3  79  97  57  64  40  19  41  69  14  39   9
  59  63  52  54  49  81  12  30  84  51] <class 'numpy.ndarray'>
Memory Space: 912


In [8]:
#Create a list of values of different type
lst=[10,"Sam",56.6,True,5+9j]
print("List Value: Type:",lst,type(lst))


List Value: Type: [10, 'Sam', 56.6, True, (5+9j)] <class 'list'>


In [9]:
#Convert List Object with Different values into ndarray Object
lst=[10,"Sam",56.6,True,5+9j]
b=an.array(lst)
print("B values:",b)
print("Type:",type(b))


B values: ['10' 'Sam' '56.6' 'True' '(5+9j)']
Type: <class 'numpy.ndarray'>


In [10]:
#Convert List Object with Different values into ndarray Object
lst=[10,20,30,405,56.7,89]
b=an.array(lst)
print("B values:",b)
print("Type:",type(b))


B values: [ 10.   20.   30.  405.   56.7  89. ]
Type: <class 'numpy.ndarray'>


In [14]:
#Convert List Object with Different values into ndarray Object
import numpy as np
lst=[10,20,30,405,567,89]
b=an.array(lst)
print("B values:",b)
print("Type:",type(b))
print("Data Type of values of ndarray",b.dtype)

B values: [ 10  20  30 405 567  89]
Type: <class 'numpy.ndarray'>
Data Type of values of ndarray int64


In [16]:
#Convert List Object with Different values into ndarray Object
import numpy as np
lst=[10,20,30,40,50,70,80,"Python"]
b=an.array(lst)
print("B values:",b)
print("Type:",type(b))
print("Data Type of values of ndarray",b.dtype)

B values: ['10' '20' '30' '40' '50' '70' '80' 'Python']
Type: <class 'numpy.ndarray'>
Data Type of values of ndarray <U21


In [17]:
#Convert List Object with Different values into ndarray Object
import numpy as np
lst=["A","b","Python"]
b=an.array(lst)
print("B values:",b)
print("Type:",type(b))
print("Data Type of values of ndarray",b.dtype)

B values: ['A' 'b' 'Python']
Type: <class 'numpy.ndarray'>
Data Type of values of ndarray <U6


In [25]:
import numpy as an
import sys
lst=[10,"Sam",56.6,True,5+9j]
b=an.array(lst)
print(b,type(b),id(b))
print("Memory Space:",sys.getsizeof(b))

['10' 'Sam' '56.6' 'True' '(5+9j)'] <class 'numpy.ndarray'> 2066526076240
Memory Space: 1392


In [29]:
import numpy as an
import sys
lst=[10,"Sam",56.6,True,5+9j]
b=an.array(lst,dtype=object)
print(b,type(b),id(b))
print("Memory Space:",sys.getsizeof(b))

[10 'Sam' 56.6 True (5+9j)] <class 'numpy.ndarray'> 2066526075472
Memory Space: 152


In [21]:
b[0]

np.str_('10')

In [30]:
b[0]=78
print(b,type(b),id(b))
print("Memory Space:",sys.getsizeof(b))

[78 'Sam' 56.6 True (5+9j)] <class 'numpy.ndarray'> 2066526075472
Memory Space: 152


In [34]:
#Complex Math operation by Traditional list object
lst=[1,2,3,4,5]
lst2=[8,7,6,5,4]
lst3=lst+lst2
print(lst3)

[1, 2, 3, 4, 5, 8, 7, 6, 5, 4]


In [36]:
#Complex Math operation by Traditional list object
lst=[1,2,3,4,5]
lst2=[8,7,6,5,4]
lst3=[]
for a,b in zip(lst,lst2):
    lst3.append(a+b)
print(lst)
print(lst2)
print(lst3)

[1, 2, 3, 4, 5]
[8, 7, 6, 5, 4]
[9, 9, 9, 9, 9]


In [33]:
#Complex Math operation by object of ndarray
lst=[1,2,3,4,5]
lst2=[8,7,6,5,4]
a=an.array(lst)
b=an.array(lst2)
c=a+b
print(a)
print(b)
print(c)

[1 2 3 4 5]
[8 7 6 5 4]
[9 9 9 9 9]
