In [32]:
#Create an Object of List
print("-"*40)
import sys
lst=[10,20,30,40,50,60,70]
print("Content of Lst=",lst)
print("Type of lst=",type(lst))
print("Memory of Traditional Python List=",sys.getsizeof(lst))
print("-"*40)

----------------------------------------
Content of Lst= [10, 20, 30, 40, 50, 60, 70]
Type of lst= <class 'list'>
Memory of Traditional Python List= 120
----------------------------------------


In [33]:
#Convert Traditional Python List into ndarray object
print("-"*50)
import numpy as np
lst=[10,20,30,40,50,60,70]
print("Content of Lst=",lst)
a=np.array(lst)
print("Content of a={}  Type={}".format(a,type(a)))
print("Memory Space of ndarray Object a=",sys.getsizeof(a))
print("-"*50)
      

--------------------------------------------------
Content of Lst= [10, 20, 30, 40, 50, 60, 70]
Content of a=[10 20 30 40 50 60 70]  Type=<class 'numpy.ndarray'>
Memory Space of ndarray Object a= 168
--------------------------------------------------


In [6]:
#Create an Object of List
print("-"*40)
import sys
lst=[10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,123,45,78,10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,123,45,78,10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,123,45,78,10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,123,45,78,10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,123,45,78,10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,123,45,78,10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,123,45,78,10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,123,45,78]
print("Content of Lst=",lst)
print("Type of lst=",type(lst))
print("Memory of Traditional Python List=",sys.getsizeof(lst))
print("-"*40)

----------------------------------------
Content of Lst= [10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78]
Type of lst= <class 'list'>
Memory of Traditional Python List= 1240
----------------------------------------


In [5]:
#Convert Traditional Python List into ndarray object
print("-"*50)
import numpy as np
lst=[10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78]
a=np.array(lst)
print("Content of a={}  Type={}".format(a,type(a)))
print("Memory Space of ndarray Object a=",sys.getsizeof(a))
print("-"*50)

--------------------------------------------------
Content of a=[ 10  20  30  40  50  60  70  15  23  56  78  90  34  66  89 123  45  78
  10  20  30  40  50  60  70  15  23  56  78  90  34  66  89 123  45  78
  10  20  30  40  50  60  70  15  23  56  78  90  34  66  89 123  45  78
  10  20  30  40  50  60  70  15  23  56  78  90  34  66  89 123  45  78
  10  20  30  40  50  60  70  15  23  56  78  90  34  66  89 123  45  78
  10  20  30  40  50  60  70  15  23  56  78  90  34  66  89 123  45  78
  10  20  30  40  50  60  70  15  23  56  78  90  34  66  89 123  45  78
  10  20  30  40  50  60  70  15  23  56  78  90  34  66  89 123  45  78]  Type=<class 'numpy.ndarray'>
Memory Space of ndarray Object a= 1264
--------------------------------------------------


In [36]:
#Create an Object of List
print("-"*40)
import sys
lst=[10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,123,45,78,10,20,30,40,\
     50,60,70,15,23,56,78,90,34,66,89,123,45,78]
print("Content of Lst=",lst)
print("Type of lst=",type(lst))
print("Memory of Traditional Python List=",sys.getsizeof(lst))
print("-"*40)

----------------------------------------
Content of Lst= [10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78]
Type of lst= <class 'list'>
Memory of Traditional Python List= 376
----------------------------------------


In [37]:
#Convert Traditional Python List into ndarray object
print("-"*50)
import numpy as np
lst=[10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,123,45,78,10,20,30,40,\
     50,60,70,15,23,56,78,90,34,66,89,123,45,78]
print("Content of Lst=",lst)
a=np.array(lst)
print("Content of a={}  Type={}".format(a,type(a)))
print("Memory Space of ndarray Object a=",sys.getsizeof(a))
print("-"*50)

--------------------------------------------------
Content of Lst= [10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78]
Content of a=[ 10  20  30  40  50  60  70  15  23  56  78  90  34  66  89 123  45  78
  10  20  30  40  50  60  70  15  23  56  78  90  34  66  89 123  45  78]  Type=<class 'numpy.ndarray'>
Memory Space of ndarray Object a= 400
--------------------------------------------------


In [39]:
#Create an Object of List--Memory Address
print("-"*40)
import sys
lst=[10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,13,45,78]
for i in lst:
    print("value:{} Addr of val:{} addr of lst:{} ".format(i,id(i),id(lst)))
print("-------------------------------")    

----------------------------------------
value:10 Addr of val:140713531663768 addr of lst:2082777552768 
value:20 Addr of val:140713531664088 addr of lst:2082777552768 
value:30 Addr of val:140713531664408 addr of lst:2082777552768 
value:40 Addr of val:140713531664728 addr of lst:2082777552768 
value:50 Addr of val:140713531665048 addr of lst:2082777552768 
value:60 Addr of val:140713531665368 addr of lst:2082777552768 
value:70 Addr of val:140713531665688 addr of lst:2082777552768 
value:15 Addr of val:140713531663928 addr of lst:2082777552768 
value:23 Addr of val:140713531664184 addr of lst:2082777552768 
value:56 Addr of val:140713531665240 addr of lst:2082777552768 
value:78 Addr of val:140713531665944 addr of lst:2082777552768 
value:90 Addr of val:140713531666328 addr of lst:2082777552768 
value:34 Addr of val:140713531664536 addr of lst:2082777552768 
value:66 Addr of val:140713531665560 addr of lst:2082777552768 
value:89 Addr of val:140713531666296 addr of lst:2082777552768 

In [40]:
#Create an Object of List--Memory Address
print("-"*40)
import sys
lst=[10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,13,45,78]
#Convert List data into  ndarray object type
a=np.array(lst)
for val in a:
    print("Value={} Addr of Val={}  Addr of ndarray object a={}".format(val,id(val),id(a)))
print("-"*40)

----------------------------------------
Value=10 Addr of Val=2082777403152  Addr of ndarray object a=2082777880912
Value=20 Addr of Val=2082777402416  Addr of ndarray object a=2082777880912
Value=30 Addr of Val=2082777401680  Addr of ndarray object a=2082777880912
Value=40 Addr of Val=2082777402416  Addr of ndarray object a=2082777880912
Value=50 Addr of Val=2082777401680  Addr of ndarray object a=2082777880912
Value=60 Addr of Val=2082777402416  Addr of ndarray object a=2082777880912
Value=70 Addr of Val=2082777401680  Addr of ndarray object a=2082777880912
Value=15 Addr of Val=2082777402416  Addr of ndarray object a=2082777880912
Value=23 Addr of Val=2082777401680  Addr of ndarray object a=2082777880912
Value=56 Addr of Val=2082777402416  Addr of ndarray object a=2082777880912
Value=78 Addr of Val=2082777401680  Addr of ndarray object a=2082777880912
Value=90 Addr of Val=2082777402416  Addr of ndarray object a=2082777880912
Value=34 Addr of Val=2082777401680  Addr of ndarray object 

In [41]:
#Vector Based Operations
lst=[10,20,30,40]
print("Content of lst={}  Type={}".format(lst,type(lst)))
#Increse Every Value of Lst by 1
lst=lst+1  # Vector Based Operations--Not Possible Traditional List

Content of lst=[10, 20, 30, 40]  Type=<class 'list'>


TypeError: can only concatenate list (not "int") to list

In [42]:
#Vector Based Operations
lst=[10,20,30,40]
print("Content of lst={}  Type={}".format(lst,type(lst)))
for i in range(len(lst)):
    lst[i]=lst[i]+1
print("Content of lst={}  Type={}".format(lst,type(lst)))    

Content of lst=[10, 20, 30, 40]  Type=<class 'list'>
Content of lst=[11, 21, 31, 41]  Type=<class 'list'>


In [44]:
#Vector Based Operations
lst=[10,20,30,40]
a=an.array(lst)
print("Content of a={}  Type={}".format(a,type(a)))
a=a+1
print("Content of a={}  Type={}".format(a,type(a)))

Content of a=[10 20 30 40]  Type=<class 'numpy.ndarray'>
Content of a=[11 21 31 41]  Type=<class 'numpy.ndarray'>


In [48]:
#Re-Shapping Mechanism
lst=[10,20,30,40,50,60,70,80,90,15,25,35]
print("Content of lst={}  Type={}".format(lst,type(lst)))
lst.reshape(4,3)

Content of lst=[10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 25, 35]  Type=<class 'list'>


AttributeError: 'list' object has no attribute 'reshape'

In [47]:
#Reshaping Mechanisms
lst=[1,2,3,4,5,6,7,8,9]
a=an.array(lst)
print(a)
a.shape=(3,3)
print(a)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
#Dimension
lst=[1,2,3,4,5,6,7,8,9]
a=an.array(lst)
print(a)
print("Dimension of a:",a.ndim)


[1 2 3 4 5 6 7 8 9]
Dimension of a: 1


In [59]:
#Dimension
lst=[1,2,3,4,5,6,7,8,9,3,4,5]
a=an.array(lst)
a.shape=(2,6)
print(a)
print("Dimension of a:",a.ndim)


[[1 2 3 4 5 6]
 [7 8 9 3 4 5]]
Dimension of a: 2


In [60]:
#Dimension
lst=[1,2,3,4,5,6,7,8]
a=an.array(lst)
a.shape=(2,2,2)
print(a)
print("Dimension of a:",a.ndim)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimension of a: 3


In [61]:
#Dimension
lst=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,25,13]
a=an.array(lst)
a.shape=(2,2,2,2)
print(a)
print("Dimension of a:",a.ndim)


[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [25 13]]]]
Dimension of a: 4


In [77]:
a.shape=(16,)
print(a,a.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 25 13] 1
