In [3]:
#Creating an object of ndarray() by random 
#syntax:var=numpy.random.randint(val) -----------> Random Number from 0 to Value-1
import numpy.random as np
ra=np.randint(10)
print("Random Value is :{} Type :{} ".format(ra,type(ra)))

Random Value is :8 Type :<class 'int'> 


In [5]:
ra=np.randint(100)
print("Random Value is :{} Type :{} ".format(ra,type(ra)))

Random Value is :50 Type :<class 'int'> 


In [6]:
ra=np.randint(100)
print("Random Value is :{} Type :{} ".format(ra,type(ra)))

Random Value is :99 Type :<class 'int'> 


In [7]:
for i in range(1,6):
    ra=np.randint(100)
    print("Random Value is :{} Type :{} ".format(ra,type(ra)))

Random Value is :59 Type :<class 'int'> 
Random Value is :81 Type :<class 'int'> 
Random Value is :50 Type :<class 'int'> 
Random Value is :82 Type :<class 'int'> 
Random Value is :1 Type :<class 'int'> 


In [ ]:
#Syntax-2: var=numpy.random.randint(low,high)-----> generates random number between low to high-1

In [8]:
ra=np.randint(10,50)
print("Random Value is :{} Type :{} ".format(ra,type(ra)))

Random Value is :12 Type :<class 'int'> 


In [9]:
ra=np.randint(10,50)
print("Random Value is :{} Type :{} ".format(ra,type(ra)))

Random Value is :43 Type :<class 'int'> 


In [10]:
ra=np.randint(1000,5000)
print("Random Value is :{} Type :{} ".format(ra,type(ra)))

Random Value is :2322 Type :<class 'int'> 


In [11]:
ra=np.randint(10000,500000)
print("Random Value is :{} Type :{} ".format(ra,type(ra)))

Random Value is :309100 Type :<class 'int'> 


In [13]:
ra=np.randint(10000,50000)
print("G-{} Type :{} ".format(ra,type(ra)))

G-28925 Type :<class 'int'> 


In [14]:
ra=np.randint(10000,50000)
print("G-{} Type :{} ".format(ra,type(ra)))

G-16625 Type :<class 'int'> 


In [15]:
for i in range(1,6):
    ra=np.randint(10000,50000)
    print("G-{} Type :{} ".format(ra,type(ra)))

G-30930 Type :<class 'int'> 
G-17434 Type :<class 'int'> 
G-33554 Type :<class 'int'> 
G-29307 Type :<class 'int'> 
G-24166 Type :<class 'int'> 


In [ ]:
#Syntax-3: var=numpy.random.randint(low,high,size)-------> \
#generates the random values between low to high with in key size if key size is 5 then it generates 5 random values type=ndarray()


In [22]:
ra=np.randint(10000,50000,6)
print("{} Type :{} ".format(ra,type(ra)))
print("Dimension:{}".format(ra.ndim))
print("Shape:{}".format(ra.shape))

[22181 28081 10337 48893 46239 13673] Type :<class 'numpy.ndarray'> 
Dimension:1
Shape:(6,)


In [23]:
ra=np.randint(10000,50000,(3,3))
print("{} Type :{} ".format(ra,type(ra)))
print("Dimension:{}".format(ra.ndim))
print("Shape:{}".format(ra.shape))

[[16348 36089 30897]
 [46085 26747 39498]
 [20437 44779 20610]] Type :<class 'numpy.ndarray'> 
Dimension:2
Shape:(3, 3)


In [24]:
ra=np.randint(10000,50000,(2,2,2))
print("{} Type :{} ".format(ra,type(ra)))
print("Dimension:{}".format(ra.ndim))
print("Shape:{}".format(ra.shape))

[[[13267 12249]
  [18637 27415]]

 [[37648 25606]
  [13088 34457]]] Type :<class 'numpy.ndarray'> 
Dimension:3
Shape:(2, 2, 2)


In [25]:
ra=np.randint(10000,50000,(2,2,2,2))
print("{} Type :{} ".format(ra,type(ra)))
print("Dimension:{}".format(ra.ndim))
print("Shape:{}".format(ra.shape))

[[[[48671 42591]
   [17652 13281]]

  [[25413 13540]
   [44925 47343]]]


 [[[49691 13044]
   [35968 29740]]

  [[10621 29151]
   [16630 41455]]]] Type :<class 'numpy.ndarray'> 
Dimension:4
Shape:(2, 2, 2, 2)


In [27]:
ra=np.randint(10000,50000,(3,2))
print("{} Type :{} ".format(ra,type(ra)))
print("Dimension:{}".format(ra.ndim))
print("Shape:{}".format(ra.shape))
print("Number of Rows:{}".format(ra.shape[0]))
print("Number of Cols:{}".format(ra.shape[1]))


[[38106 28186]
 [36564 31568]
 [47412 26399]] Type :<class 'numpy.ndarray'> 
Dimension:2
Shape:(3, 2)
Number of Rows:3
Number of Cols:2


In [31]:
ra=np.randint(10000,50000,(2,3,2))
print("{} Type :{} ".format(ra,type(ra)))
print("Dimension:{}".format(ra.ndim))
print("Shape:{}".format(ra.shape))
print("Number of Matrix:{}".format(ra.shape[0]))
print("Number of Rows:{}".format(ra.shape[1]))
print("Number of Cols:{}".format(ra.shape[2]))

[[[23358 22863]
  [48193 41229]
  [49526 26873]]

 [[17237 16736]
  [40984 39451]
  [42071 20147]]] Type :<class 'numpy.ndarray'> 
Dimension:3
Shape:(2, 3, 2)
Number of Matrix:2
Number of Rows:3
Number of Cols:2
