In [3]:
#Create an 1d Array Object with Elements
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("1D Array Data")
print(a)

1D Array Data
[10 20 30 40 50 60 70 80 90]


In [4]:
#Get the Elements 10 30 70 and 90--Method-1
#Step: Get the Indices of Elements 10 30 70 and 90
ndex=[0,2,6,8]
#Step-2: Pass the Indices Values to 1DArray
print(a[ndex])

[10 30 70 90]


In [6]:
#Get the Elements 10 90 40 10,30
a[[0,8,3,0,2]]

array([10, 90, 40, 10, 30])

In [9]:
#Create an 2d Array Object with Elements
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35,45,55,65,75]).reshape(4,4)
print("2D Array Data")
print(a)

2D Array Data
[[10 20 30 40]
 [50 60 70 80]
 [90 15 25 35]
 [45 55 65 75]]


In [10]:
#Get  10 30 25 and 45 from 2D Array-Method-1
#Step-1: Get the Row Indices of 10,30,25, and 45 from 2d Array
rdex=[0,0,2,3]
#Step-2: Get the Col Indices of 10,30,25, and 45 from 2d Array
cdex=[0,2,2,0]
#Step-3 Pass RowIndices and Colindices to 2D Array
print(a[rdex,cdex])
#Internally a[[0,0,2,3],[0,2,2,0]]---Taken (0,0),(0,2),(2,2),(3,0)

[10 30 25 45]


In [11]:
#OR
#Get  10 30 25 and 45 from 2D Array
#Step-1: Get the Row Indices of 10,30,25, and 45 from 2d Array
rowind=np.array([0,0,2,3])
#Step-2: Get the Col Indices of 10,30,25, and 45 from 2d Array
colind=np.array([0,2,2,0])
#Step-3 Pass RowIndices and Colindices to 2D Array
print(a[rowind,colind]) 
#Internally a[[0,0,2,3],[0,2,2,0]]---Taken (0,0),(0,2),(2,2),(3,0)

[10 30 25 45]


In [13]:
#Method-2
#Get  10 30 25 and 45 from 2D Array
print(a[[0,0,2,3],[0,2,2,0]])
#Internally a[[0,0,2,3],[0,2,2,0]]---Taken (0,0),(0,2),(2,2),(3,0)

[10 30 25 45]


In [14]:
#Get the Elements 40 70 45 15
print(a[[0,1,3,2],[3,2,0,1]]) #Internally Taken(0,3),(1,2),(3,0),(2,1)

[40 70 45 15]


In [15]:
#Get the Principle Diagnoal Elements
print(a[[0,1,2,3],[0,1,2,3]])

[10 60 25 75]


In [16]:
print(a)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 25 35]
 [45 55 65 75]]


In [17]:
print(a[[3,2,1,0],[0,1,2,3]])

[45 15 70 40]


In [18]:
#Create an 3d Array Object with Elements
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35,45,55,65,75]).reshape(2,4,2)
print("3D Array Data")
print(a)

3D Array Data
[[[10 20]
  [30 40]
  [50 60]
  [70 80]]

 [[90 15]
  [25 35]
  [45 55]
  [65 75]]]


In [20]:
#Method-1
#Get the Elements 10,80,25,90
#Step-1:  Get Matrix Indices of Elements 10,80,25,90
mdex=[0,0,1,1]
#Step-2:  Get Row Indices of Elements 10,80,25,90
rowind=[0,3,1,0]
#Step-3:  Get Column Indices of Elements 10,80,25,90
colind=[0,1,0,0]
#Step-3: Pass Matrix , Row and Column Indices to 3D Array
print(a[mdex,rowind,colind])

[10 80 25 90]


In [21]:
#Method-2
#Get the Elements 10,80,25,90
print(a[[0,0,1,1],[0,3,1,0],[0,1,0,0]])
#Internally Taken as (0,0,0),(0,3,1),(1,1,0),(1,0,0)

[10 80 25 90]
