In [1]:
#Numpy--Indexing Operation

In [3]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
print("Content of a:{}".format(a))
print("Dimension is:{}".format(a.ndim))

Content of a:[10 20 30 40 50 60 70 80]
Dimension is:1


In [ ]:
#Indexing Operation  on 1D

In [6]:
print(a[0])

10


In [7]:
print(a[-1])

80


In [8]:
print(a[4])

50


In [9]:
print(a[-4])

50


In [13]:
print(a[7])

80


In [15]:
print(a[len(a)-1])

80


In [16]:
print(a[-len(a)])

10


In [20]:
#get the Element 10 by using -ve Index
print(a[-a.size])

10


In [ ]:
#Indexing Operation  on 2D

In [22]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Content of a:\n{}".format(a))
print("Dimension is:{}".format(a.ndim))

Content of a:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension is:2


In [25]:
#Get the value called 50
print(a[0])
print(a[1,1])


[10 20 30]
50


In [28]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(9,1)
print("Content of a:\n{}".format(a))
print("Dimension is:{}".format(a.ndim))
print("Shape:{}".format(a.shape))

Content of a:
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]
Dimension is:2
Shape:(9, 1)


In [30]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(9,)
print("Content of a:\n{}".format(a))
print("Dimension is:{}".format(a.ndim))
print("Shape:{}".format(a.shape))

Content of a:
[10 20 30 40 50 60 70 80 90]
Dimension is:1
Shape:(9,)


In [31]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Content of a:\n{}".format(a))
print("Dimension is:{}".format(a.ndim))
print("Shape:{}".format(a.shape))

Content of a:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension is:2
Shape:(3, 3)


In [32]:
#Get the value called 10
print(a[0,0])

10


In [33]:
#Get the value called 90
print(a[-1][-1])

90


In [34]:
print(a[1,1])

50


In [37]:
print(a[2,0])
print(a[-1,-3])


70
70


In [39]:
#Indexing Operation  on 3D
import numpy as np
a=np.arange(3*3*3).reshape(3,3,3)
print("Content of ndarray")
print(a)
print("Dim of a=",a.ndim)
print("Shape of a=",a.shape)

Content of ndarray
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dim of a= 3
Shape of a= (3, 3, 3)


In [41]:
print(a[1,1,1])

13


In [42]:
print(a[-2,-2,-2])

13


In [43]:
print(a[-1])

[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [44]:
print(a[1])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [45]:
#Get 13 from 3D Array
print(a[1][1,1])

13


In [46]:
#Get 26 from 3D Array
print(a[-1,-1][-1])

26
