In [11]:
#Shuffle()
import numpy as np
a=np.arange(10,20)
print("Original Values:\n{} Type:{} id:{} ".format(a,type(a),id(a)))
np.random.shuffle(a)
print("Shuffled Values:\n{}  Type:{} id:{} ".format(a,type(a),id(a)))
print(a.shape,a.ndim)

Original Values:
[10 11 12 13 14 15 16 17 18 19] Type:<class 'numpy.ndarray'> id:2090219038128 
Shuffled Values:
[11 16 10 19 18 17 14 13 15 12]  Type:<class 'numpy.ndarray'> id:2090219038128 
(10,) 1


In [12]:
import numpy as np
a=np.arange(10,20,5)
print("Original Values:\n{} Type:{} id:{} ".format(a,type(a),id(a)))
np.random.shuffle(a)
print("Shuffled Values:\n{}  Type:{} id:{} ".format(a,type(a),id(a)))
print(a.shape,a.ndim)

Original Values:
[10 15] Type:<class 'numpy.ndarray'> id:2090219036400 
Shuffled Values:
[10 15]  Type:<class 'numpy.ndarray'> id:2090219036400 
(2,) 1


In [15]:
import numpy as np
a=np.arange(10,20,2)
print("Original Values:\n{} Type:{} id:{} ".format(a,type(a),id(a)))
np.random.shuffle(a)
print("Shuffled Values:\n{}  Type:{} id:{} ".format(a,type(a),id(a)))
print(a.shape,a.ndim)

Original Values:
[10 12 14 16 18] Type:<class 'numpy.ndarray'> id:2090219041008 
Shuffled Values:
[14 12 16 10 18]  Type:<class 'numpy.ndarray'> id:2090219041008 
(5,) 1


In [3]:
import numpy as np
a=np.arange(10,20,2)
print("Original Values:\n{} Type:{} id:{} ".format(a,type(a),id(a)))
print("-"*50)
for i in range(1,6):
    np.random.shuffle(a)
    print("Shuffled Values:{}  Type:{} id:{} ".format(a,type(a),id(a)))
print("-"*50)    
print(a.shape,a.ndim)

Original Values:
[10 12 14 16 18] Type:<class 'numpy.ndarray'> id:2560751325456 
--------------------------------------------------
Shuffled Values:[10 12 14 18 16]  Type:<class 'numpy.ndarray'> id:2560751325456 
Shuffled Values:[10 14 18 16 12]  Type:<class 'numpy.ndarray'> id:2560751325456 
Shuffled Values:[16 12 18 14 10]  Type:<class 'numpy.ndarray'> id:2560751325456 
Shuffled Values:[14 18 10 12 16]  Type:<class 'numpy.ndarray'> id:2560751325456 
Shuffled Values:[10 12 16 14 18]  Type:<class 'numpy.ndarray'> id:2560751325456 
--------------------------------------------------
(5,) 1


In [7]:
import numpy as np
a=np.array(list("MISSISSIPPI"))
print("Original Values:\n{} Type:{} id:{} ".format(a,type(a),id(a)))
print("-"*50)
for i in range(1,6):
    np.random.shuffle(a)
    print("{} Time:Shuffled Values:{}  Type:{} id:{} ".format(i,a,type(a),id(a)))
print("-"*50)    
print(a.shape,a.ndim)

Original Values:
['M' 'I' 'S' 'S' 'I' 'S' 'S' 'I' 'P' 'P' 'I'] Type:<class 'numpy.ndarray'> id:2560751954672 
--------------------------------------------------
1 Time:Shuffled Values:['M' 'S' 'I' 'P' 'I' 'S' 'S' 'S' 'I' 'P' 'I']  Type:<class 'numpy.ndarray'> id:2560751954672 
2 Time:Shuffled Values:['P' 'P' 'S' 'I' 'S' 'S' 'S' 'I' 'I' 'I' 'M']  Type:<class 'numpy.ndarray'> id:2560751954672 
3 Time:Shuffled Values:['P' 'S' 'S' 'S' 'I' 'S' 'I' 'I' 'P' 'M' 'I']  Type:<class 'numpy.ndarray'> id:2560751954672 
4 Time:Shuffled Values:['I' 'P' 'S' 'S' 'S' 'I' 'I' 'I' 'M' 'S' 'P']  Type:<class 'numpy.ndarray'> id:2560751954672 
5 Time:Shuffled Values:['P' 'P' 'I' 'M' 'I' 'I' 'I' 'S' 'S' 'S' 'S']  Type:<class 'numpy.ndarray'> id:2560751954672 
--------------------------------------------------
(11,) 1
