In [ ]:
#1. By using Looping Statements

In [3]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
print("-"*78)
print("\t1D-Array Data={} Dim:{}".format(a,a.ndim))
print("-"*78)
for i in a:
    print("\t{}".format(i))
print("-"*78)    

------------------------------------------------------------------------------
	1D-Array Data=[10 20 30 40 50 60 70 80] Dim:1
------------------------------------------------------------------------------
	10
	20
	30
	40
	50
	60
	70
	80
------------------------------------------------------------------------------


In [8]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("-"*78)
print("2D-Array Data=\n{} Dim:{}".format(a,a.ndim))
print("-"*78)
for i in a:
    for j in i:
        print("\t{}".format(j))
    print("-"*78)   
print("-"*78)    

------------------------------------------------------------------------------
2D-Array Data=
[[10 20 30]
 [40 50 60]
 [70 80 90]] Dim:2
------------------------------------------------------------------------------
	10
	20
	30
------------------------------------------------------------------------------
	40
	50
	60
------------------------------------------------------------------------------
	70
	80
	90
------------------------------------------------------------------------------
------------------------------------------------------------------------------


In [14]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,100,110,120]).reshape(2,3,2)
print("-"*78)
print("3D-Array Data=\n{} Dim:{}".format(a,a.ndim))
print("-"*78)
for i in a:
    for j in i:
        for k in j:
            print("\t{}".format(k))
        print("-"*78)   
    print("*"*78)    

------------------------------------------------------------------------------
3D-Array Data=
[[[ 10  20]
  [ 30  40]
  [ 50  60]]

 [[ 70  80]
  [ 90 100]
  [110 120]]] Dim:3
------------------------------------------------------------------------------
	10
	20
------------------------------------------------------------------------------
	30
	40
------------------------------------------------------------------------------
	50
	60
------------------------------------------------------------------------------
******************************************************************************
	70
	80
------------------------------------------------------------------------------
	90
	100
------------------------------------------------------------------------------
	110
	120
------------------------------------------------------------------------------
******************************************************************************


In [16]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,100,110,120,35,45,65,25]).reshape(2,2,2,2)
print("-"*78)
print("4D-Array Data=\n{} Dim:{}".format(a,a.ndim))
print("-"*78)
for i in a:
    for j in i:
        for k in j:
            for l in k:
                print("\t{}".format(l))
            print("-"*78)   
        print("*"*78)    

------------------------------------------------------------------------------
4D-Array Data=
[[[[ 10  20]
   [ 30  40]]

  [[ 50  60]
   [ 70  80]]]


 [[[ 90 100]
   [110 120]]

  [[ 35  45]
   [ 65  25]]]] Dim:4
------------------------------------------------------------------------------
	10
	20
------------------------------------------------------------------------------
	30
	40
------------------------------------------------------------------------------
******************************************************************************
	50
	60
------------------------------------------------------------------------------
	70
	80
------------------------------------------------------------------------------
******************************************************************************
	90
	100
------------------------------------------------------------------------------
	110
	120
------------------------------------------------------------------------------
***********************

In [ ]:
#2. By using numpy.nditer()

In [17]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print('------------------------------------------')
print("1-DArray Data={}  Dim={}".format(a,a.ndim))
print('------------------------------------------')
for val in np.nditer(a):
    print("\t{}".format(val))
print('------------------------------------------')

------------------------------------------
1-DArray Data=[10 20 30 40 50 60 70 80 90]  Dim=1
------------------------------------------
	10
	20
	30
	40
	50
	60
	70
	80
	90
------------------------------------------


In [19]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print('------------------------------------------')
print("2-DArray Data=\n{}  Dim={}".format(a,a.ndim))
print('------------------------------------------')
for val in np.nditer(a):
    print("\t{}".format(val))
print('------------------------------------------')

------------------------------------------
2-DArray Data=
[[10 20 30]
 [40 50 60]
 [70 80 90]]  Dim=2
------------------------------------------
	10
	20
	30
	40
	50
	60
	70
	80
	90
------------------------------------------


In [20]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80]).reshape(2,2,2)
print('------------------------------------------')
print("3-DArray Data=\n{}  Dim={}".format(a,a.ndim))
print('------------------------------------------')
for val in np.nditer(a):
    print("\t{}".format(val))
print('------------------------------------------')

------------------------------------------
3-DArray Data=
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]  Dim=3
------------------------------------------
	10
	20
	30
	40
	50
	60
	70
	80
------------------------------------------


In [22]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160]).reshape(2,2,2,2)
print('------------------------------------------')
print("4-DArray Data=\n{}  Dim={}".format(a,a.ndim))
print('------------------------------------------')
for val in np.nditer(a):
    print("\t{}".format(val))
print('------------------------------------------')

------------------------------------------
4-DArray Data=
[[[[ 10  20]
   [ 30  40]]

  [[ 50  60]
   [ 70  80]]]


 [[[ 90 100]
   [110 120]]

  [[130 140]
   [150 160]]]]  Dim=4
------------------------------------------
	10
	20
	30
	40
	50
	60
	70
	80
	90
	100
	110
	120
	130
	140
	150
	160
------------------------------------------


In [ ]:
 #3.By using   numpy.ndenumerate()

In [24]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print('------------------------------------------')
print("1-DArray Data={}  Dim={}".format(a,a.ndim))
print('------------------------------------------')
for iv in np.ndenumerate(a):
    print("\t{}".format(iv))
print('------------------------------------------')    

------------------------------------------
1-DArray Data=[10 20 30 40 50 60 70 80 90]  Dim=1
------------------------------------------
	((0,), np.int64(10))
	((1,), np.int64(20))
	((2,), np.int64(30))
	((3,), np.int64(40))
	((4,), np.int64(50))
	((5,), np.int64(60))
	((6,), np.int64(70))
	((7,), np.int64(80))
	((8,), np.int64(90))
------------------------------------------


In [39]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print('------------------------------------------')
print("2-DArray Data=\n{}  Dim={}".format(a,a.ndim))
print('------------------------------------------')
for iv in np.ndenumerate(a):
    print("\t{}-->{}".format(iv[0],iv[1]))
print('------------------------------------------')    

------------------------------------------
2-DArray Data=
[[10 20 30]
 [40 50 60]
 [70 80 90]]  Dim=2
------------------------------------------
	(0, 0)-->10
	(0, 1)-->20
	(0, 2)-->30
	(1, 0)-->40
	(1, 1)-->50
	(1, 2)-->60
	(2, 0)-->70
	(2, 1)-->80
	(2, 2)-->90
------------------------------------------


In [41]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print('------------------------------------------')
print("2-DArray Data=\n{}  Dim={}".format(a,a.ndim))
print('------------------------------------------')
for iv in np.ndenumerate(a):
    print("\tRow:{}-->Col:{}-->{}".format(iv[0][0],iv[0][1],iv[1]))
print('------------------------------------------')    

------------------------------------------
2-DArray Data=
[[10 20 30]
 [40 50 60]
 [70 80 90]]  Dim=2
------------------------------------------
	Row:0-->Col:0-->10
	Row:0-->Col:1-->20
	Row:0-->Col:2-->30
	Row:1-->Col:0-->40
	Row:1-->Col:1-->50
	Row:1-->Col:2-->60
	Row:2-->Col:0-->70
	Row:2-->Col:1-->80
	Row:2-->Col:2-->90
------------------------------------------


In [27]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80]).reshape(2,2,2)
print('------------------------------------------')
print("3-DArray Data=\n{}  Dim={}".format(a,a.ndim))
print('------------------------------------------')
for iv in np.ndenumerate(a):
    print("\t{}".format(iv))
print('------------------------------------------')    

------------------------------------------
3-DArray Data=
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]  Dim=3
------------------------------------------
	((0, 0, 0), np.int64(10))
	((0, 0, 1), np.int64(20))
	((0, 1, 0), np.int64(30))
	((0, 1, 1), np.int64(40))
	((1, 0, 0), np.int64(50))
	((1, 0, 1), np.int64(60))
	((1, 1, 0), np.int64(70))
	((1, 1, 1), np.int64(80))
------------------------------------------


In [46]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80]).reshape(2,2,2)
print('------------------------------------------')
print("3-DArray Data=\n{}  Dim={}".format(a,a.ndim))
print('------------------------------------------')
for iv in np.ndenumerate(a):
    print("\tMatrix:{}-->Row:{}-->Col:{}-->{}".format(iv[0][0],iv[0][1],iv[0][2],iv[1]))
print('------------------------------------------')    

------------------------------------------
3-DArray Data=
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]  Dim=3
------------------------------------------
	Matrix:0-->Row:0-->Col:0-->10
	Matrix:0-->Row:0-->Col:1-->20
	Matrix:0-->Row:1-->Col:0-->30
	Matrix:0-->Row:1-->Col:1-->40
	Matrix:1-->Row:0-->Col:0-->50
	Matrix:1-->Row:0-->Col:1-->60
	Matrix:1-->Row:1-->Col:0-->70
	Matrix:1-->Row:1-->Col:1-->80
------------------------------------------


In [29]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,1,2,3,4,5,6,7]).reshape(2,2,2,2)
print('------------------------------------------')
print("4-DArray Data=\n{}  Dim={}".format(a,a.ndim))
print('------------------------------------------')
for iv in np.ndenumerate(a):
    print("\t{}".format(iv))
print('------------------------------------------')    

------------------------------------------
4-DArray Data=
[[[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]


 [[[90  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]]  Dim=4
------------------------------------------
	((0, 0, 0, 0), np.int64(10))
	((0, 0, 0, 1), np.int64(20))
	((0, 0, 1, 0), np.int64(30))
	((0, 0, 1, 1), np.int64(40))
	((0, 1, 0, 0), np.int64(50))
	((0, 1, 0, 1), np.int64(60))
	((0, 1, 1, 0), np.int64(70))
	((0, 1, 1, 1), np.int64(80))
	((1, 0, 0, 0), np.int64(90))
	((1, 0, 0, 1), np.int64(1))
	((1, 0, 1, 0), np.int64(2))
	((1, 0, 1, 1), np.int64(3))
	((1, 1, 0, 0), np.int64(4))
	((1, 1, 0, 1), np.int64(5))
	((1, 1, 1, 0), np.int64(6))
	((1, 1, 1, 1), np.int64(7))
------------------------------------------


In [47]:
import numpy as np
a=np.arange(2*2*3*3).reshape(2,2,3,3)
print('------------------------------------------')
print("4-DArray Data\n{}  Dim={}".format(a,a.ndim))
print('------------------------------------------')
for iv in np.ndenumerate(a):
    print("Cluster:{} Matrix:{} Row:{} Col:{}--->Value:{}".format(iv[0][0],iv[0][1],iv[0][2],iv[0][3],iv[1]))
print('------------------------------------------')    

------------------------------------------
4-DArray Data
[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]]


 [[[18 19 20]
   [21 22 23]
   [24 25 26]]

  [[27 28 29]
   [30 31 32]
   [33 34 35]]]]  Dim=4
------------------------------------------
Cluster:0 Matrix:0 Row:0 Col:0--->Value:0
Cluster:0 Matrix:0 Row:0 Col:1--->Value:1
Cluster:0 Matrix:0 Row:0 Col:2--->Value:2
Cluster:0 Matrix:0 Row:1 Col:0--->Value:3
Cluster:0 Matrix:0 Row:1 Col:1--->Value:4
Cluster:0 Matrix:0 Row:1 Col:2--->Value:5
Cluster:0 Matrix:0 Row:2 Col:0--->Value:6
Cluster:0 Matrix:0 Row:2 Col:1--->Value:7
Cluster:0 Matrix:0 Row:2 Col:2--->Value:8
Cluster:0 Matrix:1 Row:0 Col:0--->Value:9
Cluster:0 Matrix:1 Row:0 Col:1--->Value:10
Cluster:0 Matrix:1 Row:0 Col:2--->Value:11
Cluster:0 Matrix:1 Row:1 Col:0--->Value:12
Cluster:0 Matrix:1 Row:1 Col:1--->Value:13
Cluster:0 Matrix:1 Row:1 Col:2--->Value:14
Cluster:0 Matrix:1 Row:2 Col:0--->Value:15
Cluster:0 Matrix:1 Row:2 Col:1--->Va

In [37]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print('------------------------------------------')
print("1-DArray Data=\n{}  Dim={}".format(a,a.ndim))
print('------------------------------------------')
for i in np.ndenumerate(a):
    print("{}---->{}".format(i[0][0],i[1]))
print('------------------------------------------')    

------------------------------------------
1-DArray Data=
[10 20 30 40 50 60 70 80 90]  Dim=1
------------------------------------------
0---->10
1---->20
2---->30
3---->40
4---->50
5---->60
6---->70
7---->80
8---->90
------------------------------------------


In [38]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print('------------------------------------------')
print("1-DArray Data={}  Dim={}".format(a,a.ndim))
print('------------------------------------------')
for iv in np.ndenumerate(a):
    print("\t{}".format(iv))
print('------------------------------------------')    

------------------------------------------
1-DArray Data=[[10 20 30]
 [40 50 60]
 [70 80 90]]  Dim=2
------------------------------------------
	((0, 0), np.int64(10))
	((0, 1), np.int64(20))
	((0, 2), np.int64(30))
	((1, 0), np.int64(40))
	((1, 1), np.int64(50))
	((1, 2), np.int64(60))
	((2, 0), np.int64(70))
	((2, 1), np.int64(80))
	((2, 2), np.int64(90))
------------------------------------------
