In [9]:
#Numpy--Slicing Operations on 1-D
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("Content of ndarray")
print(a)
print("Dim of a=",a.ndim)
print("Shape of a=",a.shape)

Content of ndarray
[10 20 30 40 50 60 70 80 90]
Dim of a= 1
Shape of a= (9,)


In [10]:
#get 30,40,50 from a
print(a[2:5])

[30 40 50]


In [11]:
#Get the Elements 60 70 80 90
print(a[5:])

[60 70 80 90]


In [14]:
#Get the Elements 30,40,50,60 with -VE Slicing
print(a[-7:-3])

[30 40 50 60]


In [15]:
#Get 10 30 50 70 90 from 2D Array
print(a[::2])

[10 30 50 70 90]


In [16]:
#Get 20 40 60 80 from 2D Array
print(a[1::2])

[20 40 60 80]


In [17]:
#Get 10 40 70 from 2DArray
print(a[::3])

[10 40 70]


In [18]:
print(a)

[10 20 30 40 50 60 70 80 90]


In [22]:
#Get 90,80,70,60 in Backward Direction from 2DArray
print(a[-1:-5:-1])

[90 80 70 60]


In [23]:
#Get 90 70 50 30  10 in Backward Direction with -VE Step
print(a[-1::-2])

[90 70 50 30 10]


In [24]:
#Get 90 70 50 30  10 in Backward Direction with +VE Step
print(a[::2][::-1])

[90 70 50 30 10]


In [25]:
#Numpy--Slicing Operations on 2-D
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,25,35,45,55,77,88,99]).reshape(4,4)
print("Content of ndarray")
print(a)
print("Dim of a=",a.ndim)
print("Shape of a=",a.shape)

Content of ndarray
[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 45]
 [55 77 88 99]]
Dim of a= 2
Shape of a= (4, 4)


In [26]:
#Get [60,70,80] from 2D Array
print(a[1:2,1:])

[[60 70 80]]


In [27]:
#Get [60,70,80] from 2D Array
print(a[1:2,1:4])

[[60 70 80]]


In [30]:
#Get 60,70,25,35 from 2D Array
print(a[1:3,1:3])

[[60 70]
 [25 35]]


In [31]:
#Get 60,70,25,35 from 2D Array
print(a[1:3:1,1:3:1])

[[60 70]
 [25 35]]


In [32]:
#Get 60,70,25,35 from 2D Array
a[1:3:,1:3:]

array([[60, 70],
       [25, 35]])

In [33]:
print(a)

[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 45]
 [55 77 88 99]]


In [34]:
print(a[1:,1:3])

[[60 70]
 [25 35]
 [77 88]]


In [35]:
print(a[1:4,1:3])

[[60 70]
 [25 35]
 [77 88]]


In [36]:
print(a[1:4:1,1:3:1])

[[60 70]
 [25 35]
 [77 88]]


In [37]:
print(a)

[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 45]
 [55 77 88 99]]


In [41]:
print(a[::2,::2])

[[10 30]
 [90 35]]


In [47]:
#Get First Column and Last Column
print(a[0:,::3])

[[10 40]
 [50 80]
 [90 45]
 [55 99]]


In [48]:
a[::,::3]

array([[10, 40],
       [50, 80],
       [90, 45],
       [55, 99]])

In [49]:
a[::1,0::3]

array([[10, 40],
       [50, 80],
       [90, 45],
       [55, 99]])

In [50]:
print(a)

[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 45]
 [55 77 88 99]]


In [55]:
#Get 50,60,70,80,55,77,88,99
print(a[1::2,::])

[[50 60 70 80]
 [55 77 88 99]]


In [56]:
#Get 50,60,70,80,55,77,88,99
print(a[1::2,:])

[[50 60 70 80]
 [55 77 88 99]]


In [57]:
a[1::2,0::1]

array([[50, 60, 70, 80],
       [55, 77, 88, 99]])

In [8]:
#Create 3D Array with Random Integer Values with shape(3,3,3)
import numpy as np
a=np.random.randint(10,20,size=(3,3,3))
print("Random Matrix:\n")
print(a)
print(a.ndim)
print(a.shape)

Random Matrix:

[[[18 18 10]
  [16 15 18]
  [15 13 13]]

 [[13 17 12]
  [18 14 17]
  [19 12 13]]

 [[14 16 16]
  [10 19 14]
  [19 12 19]]]
3
(3, 3, 3)


In [10]:
#Get First Two Matrices from 3D
a[0:2]

array([[[18, 18, 10],
        [16, 15, 18],
        [15, 13, 13]],

       [[13, 17, 12],
        [18, 14, 17],
        [19, 12, 13]]], dtype=int32)

In [11]:
#get First and Last Matrix
a[::2]

array([[[18, 18, 10],
        [16, 15, 18],
        [15, 13, 13]],

       [[14, 16, 16],
        [10, 19, 14],
        [19, 12, 19]]], dtype=int32)

In [12]:
print(a)

[[[18 18 10]
  [16 15 18]
  [15 13 13]]

 [[13 17 12]
  [18 14 17]
  [19 12 13]]

 [[14 16 16]
  [10 19 14]
  [19 12 19]]]


In [14]:
#Get All 0th row of all Columns of all Matrices
a[::,:1:,::]


array([[[18, 18, 10]],

       [[13, 17, 12]],

       [[14, 16, 16]]], dtype=int32)

In [15]:
#Get All 0th Col of all Rows of all Matrices
a[::,::,:1:]

array([[[18],
        [16],
        [15]],

       [[13],
        [18],
        [19]],

       [[14],
        [10],
        [19]]], dtype=int32)

In [16]:
print(a)

[[[18 18 10]
  [16 15 18]
  [15 13 13]]

 [[13 17 12]
  [18 14 17]
  [19 12 13]]

 [[14 16 16]
  [10 19 14]
  [19 12 19]]]


In [17]:
#Get First and Last Matrices 1St Row Elements of Correcposnding Matrices
a[::2,1:2:,::]

array([[[16, 15, 18]],

       [[10, 19, 14]]], dtype=int32)

In [18]:
print(a[::2,2::,1::])

[[[13 13]]

 [[12 19]]]


In [19]:
print(a)

[[[18 18 10]
  [16 15 18]
  [15 13 13]]

 [[13 17 12]
  [18 14 17]
  [19 12 13]]

 [[14 16 16]
  [10 19 14]
  [19 12 19]]]


In [20]:
a[::2,::2,::2]

array([[[18, 10],
        [15, 13]],

       [[14, 16],
        [19, 19]]], dtype=int32)

In [21]:
a[::2,2::2,2::2]

array([[[13]],

       [[19]]], dtype=int32)

In [22]:
a[2::,2::,::2]

array([[[19, 19]]], dtype=int32)