In [1]:
#Numpy---Filtering the Data from ndarray

In [5]:
from numpy import random as r
a=r.randint(25,55,size=12)
print("Random Elements")
print(a)
      

Random Elements
[39 27 49 27 46 27 25 30 40 45 47 52]


In [8]:
#Get the Factors of 5 --Normal Python Code
lst=[]  # Empty List
for val in a:
    if(val%5==0):
        lst.append(val)
print("Factors of 5=",lst)

Factors of 5= [np.int32(25), np.int32(30), np.int32(40), np.int32(45)]


In [9]:
#Get the Factors of 5 --Normal Python Code
lst=[val for val in a  if(val%5==0)]
print("Factors of 5=",lst)

Factors of 5= [np.int32(25), np.int32(30), np.int32(40), np.int32(45)]


In [10]:
#Create 1D Array with Random 12 Integer Values
from numpy import random as r
a=r.randint(25,55,size=12)
print("Random Elements")
print(a)

Random Elements
[37 51 48 39 34 32 35 26 26 52 39 49]


In [11]:
#Get all Factors of 5
#Step-1: Prepare the Condition with ndarray object
ba=a%5==0
print("------------------------------------------------")
print("Boolean Array={}  Type={}".format(ba,type(ba)))
print("------------------------------------------------")
#STep-2: Pass the Boolean Array to the ndarray Object
print("Factors of 5")
print(a[ba])

------------------------------------------------
Boolean Array=[False False False False False False  True False False False False False]  Type=<class 'numpy.ndarray'>
------------------------------------------------
Factors of 5
[35]


In [12]:
#Create 1D Array with Random 12 Integer Values
from numpy import random as r
a=r.randint(25,55,size=12)
print("Random Elements")
print(a)
#Get all Factors of 5
#Step-1: Prepare the Condition with ndarray object
ba=a%5==0
print("------------------------------------------------")
print("Boolean Array={}  Type={}".format(ba,type(ba)))
print("------------------------------------------------")
#STep-2: Pass the Boolean Array to the ndarray Object
print("Factors of 5")
print(a[ba])

Random Elements
[29 34 31 39 26 26 49 29 33 26 43 50]
------------------------------------------------
Boolean Array=[False False False False False False False False False False False  True]  Type=<class 'numpy.ndarray'>
------------------------------------------------
Factors of 5
[50]


In [13]:
#Create 1D Array with Random 12 Integer Values
from numpy import random as r
a=r.randint(25,55,size=12)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
#Step-1: Prepare the Condition with ndarray object
ba=(a%5==0) & (a%3==0)
print("------------------------------------------------")
print("Boolean Array={}  Type={}".format(ba,type(ba)))
print("------------------------------------------------")
#STep-2: Pass the Boolean Array to the ndarray Object
print("Factors of 5 and 3")
print(a[ba])

Random Elements
[38 49 48 27 45 45 33 48 42 33 33 42]
------------------------------------------------
Boolean Array=[False False False False  True  True False False False False False False]  Type=<class 'numpy.ndarray'>
------------------------------------------------
Factors of 5 and 3
[45 45]


In [14]:
#Create 1D Array with Random 15 Integer Values
from numpy import random as r
a=r.randint(25,55,size=15)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
print("------------------------------------------------")
print("Factors of 5 and 3")
print(a[(a%3==0)&(a%5==0)])

Random Elements
[32 29 38 28 25 27 43 31 31 46 37 44 29 36 32]
------------------------------------------------
Factors of 5 and 3
[]


In [15]:
#Create 1D Array with Random 15 Integer Values
from numpy import random as r
a=r.randint(25,55,size=15)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
print("------------------------------------------------")
print("Factors of 5 and 3")
print(a[(a%3==0)&(a%5==0)])

Random Elements
[40 48 50 42 43 51 32 54 47 41 38 39 34 53 35]
------------------------------------------------
Factors of 5 and 3
[]


In [16]:
#Create 1D Array with Random 15 Integer Values
from numpy import random as r
a=r.randint(25,55,size=15)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
print("------------------------------------------------")
print("Factors of 5 and 3")
print(a[(a%3==0)&(a%5==0)])

Random Elements
[37 35 51 30 32 26 40 54 33 42 37 46 30 39 40]
------------------------------------------------
Factors of 5 and 3
[30 30]


In [17]:
#Create 1D Array with Random 15 Integer Values
from numpy import random as r
a=r.randint(25,55,size=15)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
print("------------------------------------------------")
print("Factors of 5 and 3")
print(a[(a%3==0)&(a%5==0)])

Random Elements
[29 39 32 47 32 51 35 52 26 36 50 45 29 32 32]
------------------------------------------------
Factors of 5 and 3
[45]


In [18]:
#Create 1D Array with Random 15 Integer Values
from numpy import random as r
a=r.randint(25,55,size=15)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
print("------------------------------------------------")
print("Factors of 5 and 3")
print(a[(a%3==0)&(a%5==0)])

Random Elements
[50 26 49 28 54 27 54 50 26 50 38 36 29 48 39]
------------------------------------------------
Factors of 5 and 3
[]


In [19]:
#Create 1D Array with Random 15 Integer Values
from numpy import random as r
a=r.randint(25,91,size=15)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
print("------------------------------------------------")
print("Factors of 5 and 3")
print(a[(a%3==0)&(a%5==0)])

Random Elements
[74 89 77 72 69 71 58 34 61 79 59 50 66 65 68]
------------------------------------------------
Factors of 5 and 3
[]


In [20]:
#Create 1D Array with Random 15 Integer Values
from numpy import random as r
a=r.randint(25,55,size=15)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
print("------------------------------------------------")
print("Factors of 5 and 3")
print(a[(a%3==0)&(a%5==0)])


Random Elements
[39 51 28 36 53 45 37 36 49 47 52 34 35 41 48]
------------------------------------------------
Factors of 5 and 3
[45]


In [21]:
#Create 1D Array with Random 15 Integer Values
from numpy import random as r
a=r.randint(25,55,size=15)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
print("------------------------------------------------")
print("Factors of 5 and 3")
print(a[(a%3==0)&(a%5==0)])

Random Elements
[44 33 27 37 43 42 43 36 46 25 44 42 38 37 34]
------------------------------------------------
Factors of 5 and 3
[]
