In [16]:
#Syntax-1: var=numpy.random.randn()---->Generates random Floating Point Number 
import numpy.random as np
ra=np.randn()
print("Random Value:{} Type:{}".format(ra,type(ra)))

Random Value:1.0106075431639296 Type:<class 'float'>


In [17]:
ra=np.randn()
print("Random Value:{} Type:{}".format(ra,type(ra)))

Random Value:0.5497137433780851 Type:<class 'float'>


In [18]:
for i in range(1,6):
    ra=np.randn()
    print("Random Value:{} Type:{}".format(ra,type(ra)))

Random Value:-0.9860739088175376 Type:<class 'float'>
Random Value:-0.8173004379637719 Type:<class 'float'>
Random Value:-0.21250301150729475 Type:<class 'float'>
Random Value:0.13826226065134534 Type:<class 'float'>
Random Value:-1.2630124132070493 Type:<class 'float'>


In [19]:
#Syntax-2:varname=numpy.random.randn(Value)
#Gives  Number of Random Floating Point Values Depends on 'Value'-- +VE OR -VE---1D

In [20]:
ra=np.randn(5)
print("Random Value:{} Type:{}".format(ra,type(ra)))

Random Value:[-1.22905626  1.60843264  0.40415017  0.85667096  0.24664184] Type:<class 'numpy.ndarray'>


In [22]:
ra=np.randn(5)
print("Random Value:{} Type:{}".format(ra,type(ra)))
print("\nDim={}  Shape={}".format(ra.ndim,ra.shape))

Random Value:[-0.02790994  1.16282427  0.53277873 -1.97060064  0.29731667] Type:<class 'numpy.ndarray'>

Dim=1  Shape=(5,)


In [ ]:
#Syntax-3: varname=numpy.random.randn(Rows,Cols)
#Gives  Number of Random Floating Point Values Depends on 'Rows x Cols'-- +VE OR -VE---2D

In [25]:
ra=np.randn(3,3)
print("Random Value\n:{} Type:{}".format(ra,type(ra)))
print("\nDim={}  Shape={}".format(ra.ndim,ra.shape))

Random Value
:[[-1.08158304  0.03106796  2.16591965]
 [ 0.28952364  0.01004279 -1.36103238]
 [-1.96572178  1.28274697  1.73827004]] Type:<class 'numpy.ndarray'>

Dim=2  Shape=(3, 3)


In [28]:
ra=np.randn(5,5)
print("Random Value\n:{} Type:{}".format(ra,type(ra)))
print("\nDim={}  Shape={}".format(ra.ndim,ra.shape))

Random Value
:[[ 0.9060872   0.70274744 -1.13943726 -0.15109965 -1.30418819]
 [-0.98754421  1.82268079 -0.4649896   0.10341481 -1.36826503]
 [ 1.53634289  0.85618993  0.6846271  -0.27822873  0.5680017 ]
 [-0.41500948  0.02068818 -0.60760324  1.03584369  0.31673884]
 [ 0.83755969  1.17705352  0.14861801  0.08085818 -0.45000245]] Type:<class 'numpy.ndarray'>

Dim=2  Shape=(5, 5)


In [27]:
#Syntax-4:varname=numpy.random.randn(Matrices,Rows,Cols)
#Gives  Number of Random Floating Point Values Depends on 'Matrices x Rows x Cols'-- +VE OR -VE---3D

In [26]:
ra=np.randn(2,2,2)
print("Random Value:{} Type:{}".format(ra,type(ra)))
print("\nDim={}  Shape={}".format(ra.ndim,ra.shape))

Random Value:[[[ 0.30736571 -0.07249618]
  [-0.523633    0.53182206]]

 [[ 0.64968468 -0.06176225]
  [-0.73622147 -0.41624036]]] Type:<class 'numpy.ndarray'>

Dim=3  Shape=(2, 2, 2)


In [29]:
ra=np.randn(3,2,2)
print("Random Value:{} Type:{}".format(ra,type(ra)))
print("\nDim={}  Shape={}".format(ra.ndim,ra.shape))

Random Value:[[[-2.16714399  0.70517015]
  [ 0.884367   -0.20601814]]

 [[-0.7715253   2.35597745]
  [ 0.31266913 -1.88765577]]

 [[-1.48434634  0.31435799]
  [-0.24066445 -1.78442404]]] Type:<class 'numpy.ndarray'>

Dim=3  Shape=(3, 2, 2)
