In [1]:
#Syntax:    varname=numpy.random.normal(loc=0,scale=1,size=None)

In [3]:
import numpy.random as np
ra=np.normal()
print("Vals:{} Type:{}".format(ra,type(ra)))

Vals:0.549859143663115 Type:<class 'float'>


In [4]:
ra=np.normal()
print("Vals:{} Type:{}".format(ra,type(ra)))

Vals:0.653908368232546 Type:<class 'float'>


In [8]:
ra=np.normal(2)
print("Vals:{} Type:{}".format(ra,type(ra)))

Vals:1.9186245334059828 Type:<class 'float'>


In [31]:
ra=np.normal(5)
print("Vals:{} Type:{}".format(ra,type(ra)))


Vals:3.692361787329129 Type:<class 'float'>


In [29]:
for i in range(1,6):
    ra=np.normal(5)
    print("Vals:{} Type:{}".format(ra,type(ra)))

Vals:5.973195320736644 Type:<class 'float'>
Vals:6.634202298838867 Type:<class 'float'>
Vals:5.172098853355702 Type:<class 'float'>
Vals:5.580029045897523 Type:<class 'float'>
Vals:5.795295736623914 Type:<class 'float'>


In [11]:
for i in range(1,6):
    ra=np.normal(5)
    print("Vals:{} Type:{}".format(ra,type(ra)))

Vals:4.338450641577013 Type:<class 'float'>
Vals:4.063117947163718 Type:<class 'float'>
Vals:5.616595534757768 Type:<class 'float'>
Vals:3.6352546663271097 Type:<class 'float'>
Vals:5.477009675119986 Type:<class 'float'>


In [16]:
ra=np.normal(2,2.5)
print("Vals:{} Type:{}".format(ra,type(ra)))

Vals:2.342802937582055 Type:<class 'float'>


In [17]:
ra=np.normal(2,3)
print("Vals:{} Type:{}".format(ra,type(ra)))

Vals:4.593338952132788 Type:<class 'float'>


In [19]:
for i in range(1,6):
    ra=np.normal(2,2.5)
    print("Vals:{} Type:{}".format(ra,type(ra)))

Vals:0.8650025539864632 Type:<class 'float'>
Vals:5.576532052613199 Type:<class 'float'>
Vals:2.0010321751957774 Type:<class 'float'>
Vals:-2.0895484358044634 Type:<class 'float'>
Vals:0.3418852112287958 Type:<class 'float'>


In [20]:
for i in range(1,6):
    ra=np.normal(10,20)
    print("Vals:{} Type:{}".format(ra,type(ra)))

Vals:14.230908209237663 Type:<class 'float'>
Vals:0.07162729094277687 Type:<class 'float'>
Vals:19.8757455433678 Type:<class 'float'>
Vals:-10.8335021144619 Type:<class 'float'>
Vals:0.04461650230543057 Type:<class 'float'>


In [23]:
ra=np.normal(2,5,(3,))
print("Vals:{} Type:{}".format(ra,type(ra)))

Vals:[ 8.63851343 -2.87669505  3.1284241 ] Type:<class 'numpy.ndarray'>


In [33]:
ra=np.normal(2,5,(3,3))
print("Vals:{} Type:{}".format(ra,type(ra)))
print("Shape:{}".format(ra.shape))

Vals:[[ 4.04695967  7.72358924  1.12297084]
 [11.69557006  3.88644036  3.25019953]
 [-1.15955723  4.28530765  1.88365519]] Type:<class 'numpy.ndarray'>
Shape:(3, 3)


In [27]:
ra=np.normal(2,5,(3,5))
print("Vals:{} Type:{}".format(ra,type(ra)))
print("Shape:{}".format(ra.shape))

Vals:[[ 3.96025003  1.67629438 -0.78349235 -1.61215297 -0.67968724]
 [-1.21025738  4.73854875  7.09069692  2.4790507  -2.3131886 ]
 [ 5.1015229   6.56161169  0.37406794  1.5483247  -4.59021065]] Type:<class 'numpy.ndarray'>
Shape:(3, 5)


In [32]:
#For normal(loc,scale,size) here loc means mean,scale means standard deviation ,size is shape