In [ ]:
#Syntax:1:numpy.random.rand()

In [1]:
import numpy.random as np
a=np.rand()
print("Random Value:{} Type:{} ".format(a,type(a)))

Random Value:0.9401632481951565 Type:<class 'float'> 


In [2]:
a=np.rand()
print("Random Value:{} Type:{} ".format(a,type(a)))

Random Value:0.3432228859890656 Type:<class 'float'> 


In [3]:
#Syntax:2:numpy.random.rand(value)

In [4]:
a=np.rand(5) #5 random values are going to generate 
print("Random Value:{} Type:{} ".format(a,type(a)))

Random Value:[0.84645566 0.50096603 0.0521965  0.80467286 0.62173855] Type:<class 'numpy.ndarray'> 


In [13]:
a=np.rand(10)#10 random values are going to generate ------>1D
print("Random Value:{} Type:{} ".format(a,type(a)))
print(a.ndim)

Random Value:[0.24859378 0.4694929  0.33548538 0.83239703 0.32096397 0.46664174
 0.98505641 0.23582765 0.60894692 0.78067888] Type:<class 'numpy.ndarray'> 
1


In [ ]:
#Syntax:3:numpy.random.rand(rows,cols)

In [12]:
a=np.rand(3,2)#6 random values are going to generate ----->2D
print("Random Value:{} Type:{} ".format(a,type(a)))
print(a.shape)
print(a.ndim)

Random Value:[[0.77040999 0.87646019]
 [0.53024293 0.4223615 ]
 [0.32390646 0.5438406 ]] Type:<class 'numpy.ndarray'> 
(3, 2)
2


In [1]:
#Syntax:4:numpy.random.rand(Matrices,rows,cols)

In [6]:
import numpy.random as np
a=np.rand(2,2,2)#6 random values are going to generate-->3D
print("Random Value:\n{} Type:{} ".format(a,type(a)))
print(a.shape)
print(a.ndim)

Random Value:
[[[0.5767804  0.26607957]
  [0.51336817 0.59150262]]

 [[0.49507866 0.55135269]
  [0.40270725 0.53186151]]] Type:<class 'numpy.ndarray'> 
(2, 2, 2)
3


In [18]:
for v in a:
    print("%0.2f"%v)

0.25
0.47
0.34
0.83
0.32
0.47
0.99
0.24
0.61
0.78


In [7]:
a=np.rand(3,2)#6 random values are going to generate ----->2D
print("Random Value:{} Type:{} ".format(a,type(a)))
print(a.shape)
print(a.ndim)

Random Value:[[0.99745129 0.85199486]
 [0.60530941 0.32695187]
 [0.52775152 0.12552413]] Type:<class 'numpy.ndarray'> 
(3, 2)
2


In [9]:
a.shape=(2,3)
print(a,a.shape)

[[0.99745129 0.85199486 0.60530941]
 [0.32695187 0.52775152 0.12552413]] (2, 3)


In [12]:
a=a.reshape(3,2)
print(a,a.shape)

[[0.99745129 0.85199486]
 [0.60530941 0.32695187]
 [0.52775152 0.12552413]] (3, 2)
