In [ ]:
#5. uniform()  :  Uniform Distribution
#------------------------------------------------------------------------
#This Function Generates random sample(s) between Two Intervals(Low,High) According Programmer Choice.
#The Default random sample is low is 0.0 and high is 1.0
#Syntax-1:      varname=numpy.random.uniform()
#Syntax-2:	   varname=numpy.random.uniform(Low,High)	
#Syntax-3:	   varname=numpy.random.uniform(Low,High,size)	

In [22]:
import numpy as np
a=np.random.uniform()
print("Random Values:{} Type:{} ".format(a,type(a)))

Random Values:0.07492819018904262 Type:<class 'float'> 


In [17]:
a=np.random.uniform(10)
print("Random Values:{} Type:{} ".format(a,type(a)))

Random Values:2.871301704432047 Type:<class 'float'> 


In [18]:
a=np.random.uniform(10,20)
print("Random Values:{} Type:{} ".format(a,type(a)))

Random Values:16.784631650714502 Type:<class 'float'> 


In [19]:
a=np.random.uniform(10,20,5)#--->1D
print("Random Values:{} Type:{} ".format(a,type(a)))
print(a.shape,a.ndim)

Random Values:[10.94133102 19.55051814 11.52305872 13.69276707 19.39678203] Type:<class 'numpy.ndarray'> 
(5,) 1


In [20]:
a=np.random.uniform(10,20,(2,3))#--->2D
print("Random Values:\n{} Type:{} ".format(a,type(a)))
print(a.shape,a.ndim)

Random Values:
[[12.30386169 16.74837968 10.98135398]
 [10.80625847 13.14796047 19.44733731]] Type:<class 'numpy.ndarray'> 
(2, 3) 2


In [21]:
a=np.random.uniform(10,20,(2,2,3))#--->3D
print("Random Values:\n{} Type:{} ".format(a,type(a)))
print(a.shape,a.ndim)

Random Values:
[[[16.15822357 15.27708191 10.19812606]
  [11.95155249 18.86365868 17.87983489]]

 [[14.31325496 16.34459569 18.81057988]
  [11.2182801  11.84919406 18.63898775]]] Type:<class 'numpy.ndarray'> 
(2, 2, 3) 3
