In [10]:
#create an object of an ndarray()
import numpy as np
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a,type(a))
c=np.diag(a)
print(c,type(c))


[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[[10 20]
 [30 20]
 [30 40]] <class 'numpy.ndarray'>
[1 5 9] <class 'numpy.ndarray'>


In [11]:
#create an object of an ndarray()
import numpy as np
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a,type(a))
c=np.diag(a,k=0)
print(c,type(c))


[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[1 5 9] <class 'numpy.ndarray'>


In [12]:
#create an object of an ndarray()
import numpy as np
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a,type(a))
c=np.diag(a,k=1)
print(c,type(c))


[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[2 6] <class 'numpy.ndarray'>


In [13]:
#create an object of an ndarray()
import numpy as np
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a,type(a))
c=np.diag(a,k=2)
print(c,type(c))


[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[3] <class 'numpy.ndarray'>


In [14]:
#create an object of an ndarray()
import numpy as np
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a,type(a))
c=np.diag(a,k=3)
print(c,type(c))


[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[] <class 'numpy.ndarray'>


In [16]:
#create an object of an ndarray()
import numpy as np
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a,type(a))
c=np.diag(a,k=-1)
print(c,type(c))


[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[4 8] <class 'numpy.ndarray'>


In [17]:
#create an object of an ndarray()
import numpy as np
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a,type(a))
c=np.diag(a,k=-2)
print(c,type(c))


[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[7] <class 'numpy.ndarray'>


In [18]:
#create an object of an ndarray()
import numpy as np
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a,type(a))
c=np.diag(a,k=-3)
print(c,type(c))


[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[] <class 'numpy.ndarray'>


In [ ]:
#create an object of an ndarray()
import numpy as np
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a,type(a))
c=np.diag(a,k=3)
print(c,type(c))
