In [3]:
#create an object of an ndarray()
import numpy as np
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
b=np.array(([10,20,30],[20,30,40]))
print(a,type(a))
print(b,type(b))
c=np.vstack((a,b))
print(c,type(c))


[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[[10 20 30]
 [20 30 40]] <class 'numpy.ndarray'>
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [20 30 40]] <class 'numpy.ndarray'>


In [5]:
#create an object of an ndarray()
import numpy as np
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
b=np.array(([10,20,30],[20,30,40])).reshape(3,2)
print(a,type(a))
print(b,type(b))
c=np.vstack((a,b))
print(c,type(c))


[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[[10 20]
 [30 20]
 [30 40]] <class 'numpy.ndarray'>


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [2]:
#create an object of an ndarray()
import numpy as np
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
b=np.array(([10,20,30],[20,30,40]))
print(a,type(a))
print(b,type(b))
c=np.vstack((b,a))
print(c,type(c))


[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[[10 20 30]
 [20 30 40]] <class 'numpy.ndarray'>
[[10 20 30]
 [20 30 40]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]] <class 'numpy.ndarray'>
