In [10]:
#create an object of an ndarray()
import numpy as np
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
b=np.array(([10,20,30],[20,30,40]))
print(a,type(a))
print(b,type(b))
c=np.hstack((a,b))
print(c,type(c))


[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[[10 20 30]
 [20 30 40]] <class 'numpy.ndarray'>


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [12]:
#create an object of an ndarray()
import numpy as np
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
b=np.array(([10,20,30],[20,30,40],[10,56,78]))
print(a,type(a))
print(b,type(b))
c=np.hstack((a,b))
print(c,type(c))


[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[[10 20 30]
 [20 30 40]
 [10 56 78]] <class 'numpy.ndarray'>
[[ 1  2  3 10 20 30]
 [ 4  5  6 20 30 40]
 [ 7  8  9 10 56 78]] <class 'numpy.ndarray'>


In [15]:
#create an object of an ndarray()
import numpy as np
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
b=np.array(([10,20,30],[20,30,40])).reshape(3,2)
print(a,type(a))
print(b,type(b))
c=np.hstack((a,b))
print(c,type(c))


[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[[10 20]
 [30 20]
 [30 40]] <class 'numpy.ndarray'>
[[ 1  2  3 10 20]
 [ 4  5  6 30 20]
 [ 7  8  9 30 40]] <class 'numpy.ndarray'>
