In [1]:
#Code for Building  a Matrix with dim of 2 with All entries as 1
import numpy as np
lst=[1,1,1,1]
a=np.array(lst).reshape(2,2)
print("Zero Matrix")
print(a)
print("Dim of a=",a.ndim)

Zero Matrix
[[1 1]
 [1 1]]
Dim of a= 2


In [2]:
#Code for Building  a Matrix with dim of 2 with All entries as 1
import numpy as np
lst=[[1,1,1],[1,1,1],[1,1,1,]]
a=np.array(lst)
print("Zero Matrix")
print(a)
print("Dim of a=",a.ndim)

Zero Matrix
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Dim of a= 2


In [3]:
#Creating an ndarray object with zeros()
#All Entries with 8 ones's
import numpy as np
a=np.ones(8)
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[1. 1. 1. 1. 1. 1. 1. 1.] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:1


In [4]:
#Creating an ndarray object with zeros()
#All Entries with 8 ones's
import numpy as np
a=np.ones(8,int)
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[1 1 1 1 1 1 1 1] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:1


In [5]:
#Creating an ndarray object with zeros()
#All Entries with 8 ones's
import numpy as np
a=np.ones((4,2))
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:2


In [6]:
#Creating an ndarray object with zeros()
#All Entries with 8 ones's
import numpy as np
a=np.ones((4,2),int)
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[[1 1]
 [1 1]
 [1 1]
 [1 1]] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:2


In [10]:
#Creating an ndarray object with zeros()
#All Entries with 12 ones's
import numpy as np
a=np.ones((2,2,2))
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:3


In [12]:
#Creating an ndarray object with zeros()
#All Entries with 8 ones's
import numpy as np
a=np.ones((2,2,2),int)
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:3


In [14]:
#Creating an ndarray object with zeros()
#All Entries with 12 ones's
import numpy as np
a=np.ones((2,2,2,2))
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:4


In [15]:
#Creating an ndarray object with zeros()
#All Entries with 12 ones's
import numpy as np
a=np.ones((2,2,2,2),int)
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[[[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:4
