In [4]:
#Code for Building  a Matrix with dim of 2 with All entries as 0
import numpy as np
lst=[0,0,0,0]
a=np.array(lst).reshape(2,2)
print("Zero Matrix")
print(a)
print("Dim of a=",a.ndim)

Zero Matrix
[[0 0]
 [0 0]]
Dim of a= 2


In [5]:
#Code for Building  a Matrix with dim of 2 with All entries as 0
import numpy as np
lst=[[0,0,0],[0,0,0],[0,0,0]]
a=np.array(lst)
print("Zero Matrix")
print(a)
print("Dim of a=",a.ndim)

Zero Matrix
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Dim of a= 2


In [3]:
#Creating an ndarray object with zeros()
#All Entries with 8 Zero's
import numpy as np
a=np.zeros(8)
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[0. 0. 0. 0. 0. 0. 0. 0.] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:1


In [7]:
#Creating an ndarray object with zeros()
#All Entries with 8 Zero's
import numpy as np
a=np.zeros(8,int)
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[0 0 0 0 0 0 0 0] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:1


In [9]:
#Creating an ndarray object with zeros()
#All Entries with 9 Zero's
import numpy as np
a=np.zeros((3,3))
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:2


In [10]:
#Creating an ndarray object with zeros()
#All Entries with 9 Zero's
import numpy as np
a=np.zeros((3,3),int)
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[[0 0 0]
 [0 0 0]
 [0 0 0]] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:2


In [14]:
#Creating an ndarray object with zeros()
#All Entries with 8 Zero's
import numpy as np
a=np.zeros((2,2,2))
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:3


In [15]:
#Creating an ndarray object with zeros()
#All Entries with 8 Zero's
import numpy as np
a=np.zeros((2,2,2),int)
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:3


In [16]:
#Creating an ndarray object with zeros()
#All Entries with 12 Zero's
import numpy as np
a=np.zeros((2,2,2,2))
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:4


In [17]:
#Creating an ndarray object with zeros()
#All Entries with 12 Zero's
import numpy as np
a=np.zeros((2,2,2,2),int)
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[[[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]


 [[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:4
