In [5]:
#Create an object of nd array by eye()
import numpy as np
c=np.eye(4)
print("Content Of C:\n{}".format(c))

Content Of C:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
#Create an object of nd array by eye()
import numpy as np
c=np.eye(3)
print("Content Of C:\n{}".format(c))
print("Dimensions :{}".format(c.ndim))

Content Of C:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Dimensions :2


In [10]:
#Create an object of nd array by eye()
import numpy as np
c=np.eye(4,dtype=int)
print("Content Of C:\n{}".format(c))
print("Dimensions :{}".format(c.ndim))

Content Of C:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Dimensions :2


In [13]:
#Create an object of nd array by eye()
import numpy as np
c=np.eye((4))
print("Content Of C:\n{}".format(c))

Content Of C:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [1]:
import numpy as np
a=np.eye(3,k=1,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dim of a=",a.ndim)

Identity Matrix
[[0 1 0]
 [0 0 1]
 [0 0 0]] <class 'numpy.ndarray'>
Dim of a= 2


In [2]:
import numpy as np
a=np.eye(3,k=2,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dim of a=",a.ndim)

Identity Matrix
[[0 0 1]
 [0 0 0]
 [0 0 0]] <class 'numpy.ndarray'>
Dim of a= 2


In [3]:
import numpy as np
a=np.eye(3,k=-1,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dim of a=",a.ndim)

Identity Matrix
[[0 0 0]
 [1 0 0]
 [0 1 0]] <class 'numpy.ndarray'>
Dim of a= 2


In [4]:
import numpy as np
a=np.eye(3,k=-2,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dim of a=",a.ndim)

Identity Matrix
[[0 0 0]
 [0 0 0]
 [1 0 0]] <class 'numpy.ndarray'>
Dim of a= 2


In [5]:
import numpy as np
a=np.eye(3,2,k=1,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dim of a=",a.ndim)

Identity Matrix
[[0 1]
 [0 0]
 [0 0]] <class 'numpy.ndarray'>
Dim of a= 2


In [6]:
import numpy as np
a=np.eye(7,8,k=1,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dim of a=",a.ndim)

Identity Matrix
[[0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]] <class 'numpy.ndarray'>
Dim of a= 2


In [7]:
import numpy as np
a=np.eye(3,4,k=1,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dim of a=",a.ndim)

Identity Matrix
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] <class 'numpy.ndarray'>
Dim of a= 2


In [9]:
import numpy as np
a=np.eye(4,3,k=1,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dim of a=",a.ndim)

Identity Matrix
[[0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]] <class 'numpy.ndarray'>
Dim of a= 2


In [12]:
import numpy as np
a=np.eye(5,5,k=5,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dim of a=",a.ndim)

Identity Matrix
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] <class 'numpy.ndarray'>
Dim of a= 2
