In [2]:
#Code for Building  a Matrix with dim of 2 with All entries as 5
import numpy as np
lst=[5,5,5,5]
a=np.array(lst).reshape(2,2)
print("Zero Matrix")
print(a)
print("Dim of a=",a.ndim)

Zero Matrix
[[5 5]
 [5 5]]
Dim of a= 2


In [5]:
#Creating an ndarray object by full()
a=np.full(5,5)
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[5 5 5 5 5] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:1


In [7]:
#Creating an ndarray object by full()
a=np.full((3,2),fill_value=5)
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[[5 5]
 [5 5]
 [5 5]] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:2


In [8]:
#Creating an ndarray object by full()
a=np.full(shape=(2,2,2,2),fill_value=9,dtype=float)
print("Content of a\n{} Type:{} ".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a
[[[[9. 9.]
   [9. 9.]]

  [[9. 9.]
   [9. 9.]]]


 [[[9. 9.]
   [9. 9.]]

  [[9. 9.]
   [9. 9.]]]] Type:<class 'numpy.ndarray'> 
--------------------------------------------------
Dimensions of a:4
