In [4]:
#Creating ndarray object by arange()
import numpy as np
a=np.arange(10)
print("content of a={}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  
print("Shape of ndarray={}".format(a.shape))   
print("Size of ndarray={}".format(a.size)) 

content of a=[0 1 2 3 4 5 6 7 8 9]  Type=<class 'numpy.ndarray'>
Dimension ndarray =1
Shape of ndarray=(10,)
Size of ndarray=10


In [5]:
#Creating ndarray object by arange()
import numpy as np
a=np.arange(10).reshape(5,2)
print("content of a={}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  
print("Shape of ndarray={}".format(a.shape))   
print("Size of ndarray={}".format(a.size)) 

content of a=[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =2
Shape of ndarray=(5, 2)
Size of ndarray=10


In [7]:
#Creating ndarray object by arange()
import numpy as np
a=np.arange(8).reshape(2,2,2)
print("content of a=\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  
print("Shape of ndarray={}".format(a.shape))   
print("Size of ndarray={}".format(a.size)) 

content of a=
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =3
Shape of ndarray=(2, 2, 2)
Size of ndarray=8


In [9]:
#Creating ndarray object by arange()
import numpy as np
a=np.arange(16).reshape(2,2,2,2)
print("content of a=\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  
print("Shape of ndarray={}".format(a.shape))   
print("Size of ndarray={}".format(a.size)) 

content of a=
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =4
Shape of ndarray=(2, 2, 2, 2)
Size of ndarray=16


In [10]:
#Creating ndarray object by arange()
import numpy as np
a=np.arange(10,20,3)
print("content of a={}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  
print("Shape of ndarray={}".format(a.shape))   
print("Size of ndarray={}".format(a.size)) 

content of a=[10 13 16 19]  Type=<class 'numpy.ndarray'>
Dimension ndarray =1
Shape of ndarray=(4,)
Size of ndarray=4


In [12]:
#Creating ndarray object by arange()
import numpy as np
a=np.arange(10,20,3).reshape(2,2)
print("content of a=\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  
print("Shape of ndarray={}".format(a.shape))   
print("Size of ndarray={}".format(a.size)) 

content of a=
[[10 13]
 [16 19]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =2
Shape of ndarray=(2, 2)
Size of ndarray=4


In [13]:
#Creating ndarray object by arange()
import numpy as np
a=np.arange(10,20,0.5)
print("content of a={}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  
print("Shape of ndarray={}".format(a.shape))   
print("Size of ndarray={}".format(a.size)) 

content of a=[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5]  Type=<class 'numpy.ndarray'>
Dimension ndarray =1
Shape of ndarray=(20,)
Size of ndarray=20


In [16]:
#Creating ndarray object by arange()
import numpy as np
a=np.arange(10,21,0.5).reshape(11,2)
print("content of a={}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  
print("Shape of ndarray={}".format(a.shape))   
print("Size of ndarray={}".format(a.size)) 

content of a=[[10.  10.5]
 [11.  11.5]
 [12.  12.5]
 [13.  13.5]
 [14.  14.5]
 [15.  15.5]
 [16.  16.5]
 [17.  17.5]
 [18.  18.5]
 [19.  19.5]
 [20.  20.5]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =2
Shape of ndarray=(11, 2)
Size of ndarray=22
