In [5]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=10
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:{} Type:{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:10 Type:<class 'int'>
Content of ndarray:10 Type:<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:0
Shape of ndarray:()
Size of ndarray:1
--------------------------------------------------


In [6]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=10.98
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:{} Type:{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:10.98 Type:<class 'float'>
Content of ndarray:10.98 Type:<class 'numpy.ndarray'>
Data type of ndarray:float64
Dimensions of ndarray:0
Shape of ndarray:()
Size of ndarray:1
--------------------------------------------------


In [7]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=10+98j
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:{} Type:{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:(10+98j) Type:<class 'complex'>
Content of ndarray:(10+98j) Type:<class 'numpy.ndarray'>
Data type of ndarray:complex128
Dimensions of ndarray:0
Shape of ndarray:()
Size of ndarray:1
--------------------------------------------------


In [9]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a="SAAYARA"
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:{} Type:{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:SAAYARA Type:<class 'str'>
Content of ndarray:SAAYARA Type:<class 'numpy.ndarray'>
Data type of ndarray:<U7
Dimensions of ndarray:0
Shape of ndarray:()
Size of ndarray:1
--------------------------------------------------


In [10]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=range(10)
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:{} Type:{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:range(0, 10) Type:<class 'range'>
Content of ndarray:[0 1 2 3 4 5 6 7 8 9] Type:<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:1
Shape of ndarray:(10,)
Size of ndarray:10
--------------------------------------------------


In [11]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=range(10,21,2)
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:{} Type:{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:range(10, 21, 2) Type:<class 'range'>
Content of ndarray:[10 12 14 16 18 20] Type:<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:1
Shape of ndarray:(6,)
Size of ndarray:6
--------------------------------------------------


In [13]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=range(10,0,-2)
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:{} Type:{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:range(10, 0, -2) Type:<class 'range'>
Content of ndarray:[10  8  6  4  2] Type:<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:1
Shape of ndarray:(5,)
Size of ndarray:5
--------------------------------------------------


In [14]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=range(0,9)
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:{} Type:{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:range(0, 9) Type:<class 'range'>
Content of ndarray:[0 1 2 3 4 5 6 7 8] Type:<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:1
Shape of ndarray:(9,)
Size of ndarray:9
--------------------------------------------------


In [24]:
#Re-shaping of ndarray object --by attribute called shape
print("-"*50)
b.shape=(3,3)
print("Content of ndarray:\n{} \nType:{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)

--------------------------------------------------
Content of ndarray:
[[0 1 2]
 [3 4 5]
 [6 7 8]] 
Type:<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:2
Shape of ndarray:(3, 3)
Size of ndarray:9
--------------------------------------------------


In [25]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=range(16)
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:{} Type:{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:range(0, 16) Type:<class 'range'>
Content of ndarray:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] Type:<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:1
Shape of ndarray:(16,)
Size of ndarray:16
--------------------------------------------------


In [26]:
#Re-shaping of ndarray object --by attribute called shape
print("-"*50)
b.shape=(4,4)
print("Content of ndarray:\n{} \nType:{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)

--------------------------------------------------
Content of ndarray:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 
Type:<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:2
Shape of ndarray:(4, 4)
Size of ndarray:16
--------------------------------------------------


In [31]:
#Re-shaping of ndarray object --by attribute called shape
print("-"*50)
b.shape=(2,2,4)
print("Content of ndarray:\n{} \nType:{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)

--------------------------------------------------
Content of ndarray:
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] 
Type:<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:3
Shape of ndarray:(2, 2, 4)
Size of ndarray:16
--------------------------------------------------


In [33]:
#Re-shaping of ndarray object --by attribute called shape
print("-"*50)
b.shape=(2,2,2,2)
print("Content of ndarray:\n{} \nType:{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)

--------------------------------------------------
Content of ndarray:
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]] 
Type:<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:4
Shape of ndarray:(2, 2, 2, 2)
Size of ndarray:16
--------------------------------------------------


In [41]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=range(24)
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
b=b.reshape(6,4)
print("Content of ndarray:\n{} Type:\n{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:range(0, 24) Type:<class 'range'>
Content of ndarray:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] Type:
<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:2
Shape of ndarray:(6, 4)
Size of ndarray:24
--------------------------------------------------


In [43]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=range(24)
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a,dtype=float)
b=b.reshape(6,4)
print("Content of ndarray:\n{} Type:\n{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:range(0, 24) Type:<class 'range'>
Content of ndarray:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]] Type:
<class 'numpy.ndarray'>
Data type of ndarray:float64
Dimensions of ndarray:2
Shape of ndarray:(6, 4)
Size of ndarray:24
--------------------------------------------------


In [46]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=[10,20,30,40,50,60,70,80,90]
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:\n{} Type:\n{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:[10, 20, 30, 40, 50, 60, 70, 80, 90] Type:<class 'list'>
Content of ndarray:
[10 20 30 40 50 60 70 80 90] Type:
<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:1
Shape of ndarray:(9,)
Size of ndarray:9
--------------------------------------------------


In [47]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=[10,20,30,40,50,60,70,80,90]
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
b=b.reshape(3,3)
print("Content of ndarray:\n{} Type:\n{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:[10, 20, 30, 40, 50, 60, 70, 80, 90] Type:<class 'list'>
Content of ndarray:
[[10 20 30]
 [40 50 60]
 [70 80 90]] Type:
<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:2
Shape of ndarray:(3, 3)
Size of ndarray:9
--------------------------------------------------


In [49]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=[10,20,30,40,50,60,70,80,90]
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a,float).reshape(3,3)
print("Content of ndarray:\n{} Type:\n{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:[10, 20, 30, 40, 50, 60, 70, 80, 90] Type:<class 'list'>
Content of ndarray:
[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]] Type:
<class 'numpy.ndarray'>
Data type of ndarray:float64
Dimensions of ndarray:2
Shape of ndarray:(3, 3)
Size of ndarray:9
--------------------------------------------------


In [70]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=(10,20,30,40,50,60,70,80,90)
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a,float).reshape(3,3)
print("Content of ndarray:\n{} Type:\n{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:(10, 20, 30, 40, 50, 60, 70, 80, 90) Type:<class 'tuple'>
Content of ndarray:
[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]] Type:
<class 'numpy.ndarray'>
Data type of ndarray:float64
Dimensions of ndarray:2
Shape of ndarray:(3, 3)
Size of ndarray:9
--------------------------------------------------


In [57]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=[[10,20],[30,40],[50,60],[70,80]]
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:\n{} Type:\n{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:[[10, 20], [30, 40], [50, 60], [70, 80]] Type:<class 'list'>
Content of ndarray:
[[10 20]
 [30 40]
 [50 60]
 [70 80]] Type:
<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:2
Shape of ndarray:(4, 2)
Size of ndarray:8
--------------------------------------------------


In [58]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=[[10,20],[30,40]],[[50,60],[70,80]]
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:\n{} Type:\n{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)


--------------------------------------------------
Contect of a:([[10, 20], [30, 40]], [[50, 60], [70, 80]]) Type:<class 'tuple'>
Content of ndarray:
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]] Type:
<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:3
Shape of ndarray:(2, 2, 2)
Size of ndarray:8
--------------------------------------------------


In [59]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=(([10,20],[30,40]),([50,60],[70,80]))
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:\n{} Type:\n{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)

--------------------------------------------------
Contect of a:(([10, 20], [30, 40]), ([50, 60], [70, 80])) Type:<class 'tuple'>
Content of ndarray:
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]] Type:
<class 'numpy.ndarray'>
Data type of ndarray:int64
Dimensions of ndarray:3
Shape of ndarray:(2, 2, 2)
Size of ndarray:8
--------------------------------------------------


In [62]:
b.astype(complex)

array([[[10.+0.j, 20.+0.j],
        [30.+0.j, 40.+0.j]],

       [[50.+0.j, 60.+0.j],
        [70.+0.j, 80.+0.j]]])

In [63]:
b.astype(int)

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [65]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a={1,2,3,4,5,6,76,8}
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:\n{} Type:{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)

--------------------------------------------------
Contect of a:{1, 2, 3, 4, 5, 6, 8, 76} Type:<class 'set'>
Content of ndarray:
{1, 2, 3, 4, 5, 6, 8, 76} Type:<class 'numpy.ndarray'>
Data type of ndarray:object
Dimensions of ndarray:0
Shape of ndarray:()
Size of ndarray:1
--------------------------------------------------


In [66]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a={1:"sai",2:"byee",3:"fahhhhh"}
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:\n{} Type:\n{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)

--------------------------------------------------
Contect of a:{1: 'sai', 2: 'byee', 3: 'fahhhhh'} Type:<class 'dict'>
Content of ndarray:
{1: 'sai', 2: 'byee', 3: 'fahhhhh'} Type:
<class 'numpy.ndarray'>
Data type of ndarray:object
Dimensions of ndarray:0
Shape of ndarray:()
Size of ndarray:1
--------------------------------------------------


In [68]:
#creating an object of ndarray object by using array()
import numpy as np
print("-"*50)
a=None
print("Contect of a:{} Type:{}".format(a,type(a)))
b=np.array(a)
print("Content of ndarray:\n{} Type:\n{}".format(b,type(b)))
print("Data type of ndarray:{}".format(b.dtype))
print("Dimensions of ndarray:{}".format(b.ndim))
print("Shape of ndarray:{}".format(b.shape))
print("Size of ndarray:{}".format(b.size))
print("-"*50)

--------------------------------------------------
Contect of a:None Type:<class 'NoneType'>
Content of ndarray:
None Type:
<class 'numpy.ndarray'>
Data type of ndarray:object
Dimensions of ndarray:0
Shape of ndarray:()
Size of ndarray:1
--------------------------------------------------


In [71]:
#Final conclusion
# for int.float.complex.str.set.dict.None for them doesn't have any type of dimensions and shape
# for range.list.Tuple.innerlist.Tunplesoflist for them have type of dimensions and shape
