In [3]:
#Create an ndarray object of 2D Matrix identity
import numpy as np
lst=[0,1,1,0]
a=np.array(lst).reshape(2,2)
print("Content of a:\n{} Type:{}".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a:
[[0 1]
 [1 0]] Type:<class 'numpy.ndarray'>
--------------------------------------------------
Dimensions of a:2


In [4]:
#create an object of ndarray ny using identity()
a=np.identity(2)
print("Content of a:\n{} Type:{}".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a:
[[1. 0.]
 [0. 1.]] Type:<class 'numpy.ndarray'>
--------------------------------------------------
Dimensions of a:2


In [5]:
#create an object of ndarray ny using identity()
a=np.identity(2,int)
print("Content of a:\n{} Type:{}".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a:
[[1 0]
 [0 1]] Type:<class 'numpy.ndarray'>
--------------------------------------------------
Dimensions of a:2


In [8]:
#create an object of ndarray ny using identity()
a=np.identity(3)
print("Content of a:\n{} Type:{}".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] Type:<class 'numpy.ndarray'>
--------------------------------------------------
Dimensions of a:2


In [9]:
#create an object of ndarray ny using identity()
a=np.identity(4)
print("Content of a:\n{} Type:{}".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] Type:<class 'numpy.ndarray'>
--------------------------------------------------
Dimensions of a:2


In [14]:
#create an object of ndarray ny using identity() 3D
a=np.identity(4).reshape(2,4,2)
print("Content of a:\n{} Type:{}".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a:
[[[1. 0.]
  [0. 0.]
  [0. 1.]
  [0. 0.]]

 [[0. 0.]
  [1. 0.]
  [0. 0.]
  [0. 1.]]] Type:<class 'numpy.ndarray'>
--------------------------------------------------
Dimensions of a:3


In [16]:
#create an object of ndarray ny using identity() 4D
a=np.identity(4).reshape(2,2,2,2)
print("Content of a:\n{} Type:{}".format(a,type(a)))
print("-"*50)
print("Dimensions of a:{}".format(a.ndim))

Content of a:
[[[[1. 0.]
   [0. 0.]]

  [[0. 1.]
   [0. 0.]]]


 [[[0. 0.]
   [1. 0.]]

  [[0. 0.]
   [0. 1.]]]] Type:<class 'numpy.ndarray'>
--------------------------------------------------
Dimensions of a:4
